/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadorabasica27anggelorosales;

import java.util.logging.Level;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Pamela
 */
public class jfrmCalc extends javax.swing.JFrame {


    //Variables,publicas,privadas,globales y genericas
    private String entrada="";
    private double numero1,numero2;
    private String operador;
    
    public jfrmCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jbtn5 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDivi = new javax.swing.JButton();
        jbtnIgual = new javax.swing.JButton();
        jbtnSuma = new javax.swing.JButton();
        jbtnPunto = new javax.swing.JButton();
        jbtnPorcen = new javax.swing.JButton();
        jbtnRaiz = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtnResta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtnQuitar = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnBorrar = new javax.swing.JButton();


        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("3");

        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton14.setText("4");

        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton15.setText("5");

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton13.setText("6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jbtn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(this::jbtn7ActionPerformed);

        jbtn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(this::jbtn8ActionPerformed);

        jbtnQuitar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnQuitar.setText("C");
        jbtnQuitar.addActionListener(this::jbtnQuitarActionPerformed);

        jbtn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(this::jbtn9ActionPerformed);

        jbtnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnBorrar.setText("AC");
        jbtnBorrar.addActionListener(this::jbtnBorrarActionPerformed);

        jbtn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(this::jbtn5ActionPerformed);

        jbtn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(this::jbtn4ActionPerformed);

        jbtn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(this::jbtn6ActionPerformed);

        jbtn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(this::jbtn1ActionPerformed);

        jbtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(this::jbtn2ActionPerformed);

        jbtn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(this::jbtn3ActionPerformed);

        jbtn0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(this::jbtn0ActionPerformed);

        jbtnDivi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnDivi.setText("/");
        jbtnDivi.addActionListener(this::jbtnDiviActionPerformed);

        jbtnIgual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnIgual.setText("=");
        jbtnIgual.addActionListener(this::jbtnIgualActionPerformed);

        jbtnSuma.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnSuma.setText("+");
        jbtnSuma.addActionListener(this::jbtnSumaActionPerformed);

        jbtnPunto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPunto.setText(".");
        jbtnPunto.addActionListener(this::jbtnPuntoActionPerformed);

        jbtnPorcen.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPorcen.setText("%");
        jbtnPorcen.addActionListener(this::jbtnPorcenActionPerformed);

        jbtnRaiz.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRaiz.setText("√");
        jbtnRaiz.addActionListener(this::jbtnRaizActionPerformed);

        jbtnMulti.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnMulti.setText("X");
        jbtnMulti.addActionListener(this::jbtnMultiActionPerformed);

        jbtnResta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnResta.setText("-");
        jbtnResta.addActionListener(this::jbtnRestaActionPerformed);
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn7)
                    .addComponent(jbtn8)
                    .addComponent(jbtn9)
                    .addComponent(jbtnBorrar)
                    .addComponent(jbtnDivi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn5)
                    .addComponent(jbtn4)
                    .addComponent(jbtn6)
                    .addComponent(jbtnQuitar)
                    .addComponent(jbtnMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1)
                    .addComponent(jbtn2)
                    .addComponent(jbtn3)
                    .addComponent(jbtnPorcen)
                    .addComponent(jbtnResta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn0)
                    .addComponent(jbtnIgual)
                    .addComponent(jbtnSuma)
                    .addComponent(jbtnPunto)
                    .addComponent(jbtnRaiz))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSumaActionPerformed
    if (entrada.equals("") == false) {

        if (numero1 != 0) {
            numero2 = Double.parseDouble(entrada);

            if (operador.equals("+")) {
                numero1 = numero1 + numero2;
            }
            if (operador.equals("-")) {
                numero1 = numero1 - numero2;
            }
            if (operador.equals("X")) {
                numero1 = numero1 * numero2;
            }
            if (operador.equals("/")) {
                if (numero2 == 0) {
                    jtxtCantidad.setText("Error");
                    entrada = "";
                    return;
                }
                numero1 = numero1 / numero2;
            }

        } else {
            numero1 = Double.parseDouble(entrada);
        }

        operador = "+";
        entrada = "";        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSumaActionPerformed
        }                                        

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
    if (entrada.equals("") == false) {
        numero2 = Double.parseDouble(entrada);

        if (operador.equals("+")) {
            numero1 = numero1 + numero2;
        }
        if (operador.equals("-")) {
            numero1 = numero1 - numero2;
        }
        if (operador.equals("X")) {
            numero1 = numero1 * numero2;
        }
        if (operador.equals("/")) {
            if (numero2 == 0) {
                jtxtCantidad.setText("Error");
                entrada = "";
                return;
            }
            numero1 = numero1 / numero2;
        }

        entrada = String.valueOf(numero1);
        jtxtCantidad.setText(entrada);
        operador = "";
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnIgualActionPerformed

    private void jbtnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuntoActionPerformed
      if (entrada.contains(".") == false) {
        entrada = entrada + ".";
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPuntoActionPerformed
         }                                         

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
     entrada= entrada+0;
        jtxtCantidad.setText(entrada);         // TODO add your handling code here:
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
     entrada= entrada+1;
        jtxtCantidad.setText(entrada);    // TODO add your handling code here:
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
     entrada= entrada+2;
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
     entrada= entrada+3;
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
     entrada= entrada+4;
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
     entrada= entrada+5;
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
     entrada= entrada+6;
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
     entrada= entrada+7;
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
     entrada= entrada+8;
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
     entrada= entrada+9;
        jtxtCantidad.setText(entrada);        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRaizActionPerformed
     if (entrada.equals("") == false) {
        jtxtCantidad.setText("√" + entrada); 

        double valor = Double.parseDouble(entrada);

        if (valor >= 0) {
            valor = Math.sqrt(valor);
            entrada = String.valueOf(valor);
            jtxtCantidad.setText("√ = " + entrada); 
        } else {
            jtxtCantidad.setText("Error");
            entrada = "";
        }
    }
    }//GEN-LAST:event_jbtnRaizActionPerformed

    private void jbtnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuitarActionPerformed
    if (entrada.equals("") == false) {
        entrada = entrada.substring(0, entrada.length() - 1);

        if (entrada.equals("")) {
            entrada = "";
        }

        jtxtCantidad.setText(entrada);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnQuitarActionPerformed

    private void jbtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrarActionPerformed
    entrada = "";
    numero1 = 0;
    numero2 = 0;
    operador = "";
    jtxtCantidad.setText("");        
    }//GEN-LAST:event_jbtnBorrarActionPerformed

    private void jbtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestaActionPerformed
     if (entrada.equals("") == false) {

        if (numero1 != 0) {
            numero2 = Double.parseDouble(entrada);

            if (operador.equals("+")) {
                numero1 = numero1 + numero2;
            }
            if (operador.equals("-")) {
                numero1 = numero1 - numero2;
            }
            if (operador.equals("X")) {
                numero1 = numero1 * numero2;
            }
            if (operador.equals("/")) {
                if (numero2 == 0) {
                    jtxtCantidad.setText("Error");
                    entrada = "";
                    return;
                }
                numero1 = numero1 / numero2;
            }

        } else {
            numero1 = Double.parseDouble(entrada);
        }

        operador = "-";
        entrada = "";
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRestaActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
     if (entrada.equals("") == false) {

        if (numero1 != 0) {
            numero2 = Double.parseDouble(entrada);

            if (operador.equals("+")) {
                numero1 = numero1 + numero2;
            }
            if (operador.equals("-")) {
                numero1 = numero1 - numero2;
            }
            if (operador.equals("X")) {
                numero1 = numero1 * numero2;
            }
            if (operador.equals("/")) {
                if (numero2 == 0) {
                    jtxtCantidad.setText("Error");
                    entrada = "";
                    return;
                }
                numero1 = numero1 / numero2;
            }

        } else {
            numero1 = Double.parseDouble(entrada);
        }

        operador = "X";
        entrada = "";
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiviActionPerformed
     if (entrada.equals("") == false) {

        if (numero1 != 0) {
            numero2 = Double.parseDouble(entrada);

            if (operador.equals("+")) {
                numero1 = numero1 + numero2;
            }
            if (operador.equals("-")) {
                numero1 = numero1 - numero2;
            }
            if (operador.equals("X")) {
                numero1 = numero1 * numero2;
            }
            if (operador.equals("/")) {
                if (numero2 == 0) {
                    jtxtCantidad.setText("Error");
                    entrada = "";
                    return;
                }
                numero1 = numero1 / numero2;
            }

        } else {
            numero1 = Double.parseDouble(entrada);
        }

        operador = "/";
        entrada = "";
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDiviActionPerformed

    private void jbtnPorcenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPorcenActionPerformed
    if (entrada.equals("") == false) {

        double valor = Double.parseDouble(entrada);

        if (numero1 != 0) {
            valor = (numero1 * valor) / 100;
        } else {
            valor = valor / 100;
        }

        entrada = String.valueOf(valor);
        jtxtCantidad.setText(entrada);
    }
    }//GEN-LAST:event_jbtnPorcenActionPerformed
                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, (UnsupportedLookAndFeelException) ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmCalc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBorrar;
    private javax.swing.JButton jbtnDivi;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnPorcen;
    private javax.swing.JButton jbtnPunto;
    private javax.swing.JButton jbtnQuitar;
    private javax.swing.JButton jbtnRaiz;
    private javax.swing.JButton jbtnResta;
    private javax.swing.JButton jbtnSuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables

    private static class logger {

        private static void log(Level SEVERE, Object object, UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public logger() {
        }
    }
}
